Anatomic:
    'brain':0,
    'breast':1,
    'bladder':2,
    'kidney':3,
    'prostate':4,
    'testis':5,
    'lung':6,
    'pancreas':7,
    'liver':8,
    'skin':9,
    'ovary':10,
    'cervix':11,
    'uterus':12,
    'colon':13,
    'esophagus':14,
    'stomach':15,
    'thyroid':16,
    'adrenal gland':17,
    'soft tissue':18
